import type { Movie } from '../types/movies/Movie';
import type { MovieDetails } from '../types/movies/MovieDetails';

const mockMovies: Movie[] = [
  {
    adult: false,
    backdrop_path: '/ovZasZ9EeZcp6UsrElkQ63hFCd.jpg',
    id: 1087192,
    title: 'How to Train Your Dragon',
    original_title: 'How to Train Your Dragon',
    overview:
      'On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.',
    poster_path: '/q5pXRYTycaeW6dEgsCrd4mYPmxM.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [14, 10751, 28],
    popularity: 874.3321,
    release_date: '2025-06-06',
    video: false,
    vote_average: 8.084,
    vote_count: 829,
  },
  {
    adult: false,
    backdrop_path: '/ApRxyHFuvv5yghedxXPJSm9FEDe.jpg',
    id: 1061474,
    title: 'Superman',
    original_title: 'Superman',
    overview:
      'Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.',
    poster_path: '/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [878, 12, 28],
    popularity: 497.0571,
    release_date: '2025-07-09',
    video: false,
    vote_average: 7.46,
    vote_count: 791,
  },
  {
    adult: false,
    backdrop_path: '/5l3Ge1f3944AsDiiDXWQ3RSZ0Bg.jpg',
    id: 1071585,
    title: 'M3GAN 2.0',
    original_title: 'M3GAN 2.0',
    overview:
      "After the underlying tech for M3GAN is stolen and misused by a powerful defense contractor to create a military-grade weapon known as Amelia, M3GAN's creator Gemma realizes that the only option is to resurrect M3GAN and give her a few upgrades, making her faster, stronger, and more lethal.",
    poster_path: '/4a63rQqIDTrYNdcnTXdPsQyxVLo.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [28, 878, 53],
    popularity: 650.7798,
    release_date: '2025-06-25',
    video: false,
    vote_average: 7.735,
    vote_count: 270,
  },
  {
    adult: false,
    backdrop_path: '/s94NjfKkcSczZ1FembwmQZwsuwY.jpg',
    id: 617126,
    title: 'The Fantastic Four: First Steps',
    original_title: 'The Fantastic Four: First Steps',
    overview:
      "Against the vibrant backdrop of a 1960s-inspired, retro-futuristic world, Marvel's First Family is forced to balance their roles as heroes with the strength of their family bond, while defending Earth from a ravenous space god called Galactus and his enigmatic Herald, Silver Surfer.",
    poster_path: '/x26MtUlwtWD26d0G0FXcppxCJio.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [878, 12],
    popularity: 66.7218,
    release_date: '2025-07-23',
    video: false,
    vote_average: 0.0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/y08GwxG5uDtHJkOf8w5dnygKyvz.jpg',
    id: 931285,
    title: 'Mortal Kombat II',
    original_title: 'Mortal Kombat II',
    overview:
      'The fan favorite champions—now joined by Johnny Cage himself—are pitted against one another in the ultimate, no-holds barred, gory battle to defeat the dark rule of Shao Kahn that threatens the very existence of the Earthrealm and its defenders.',
    poster_path: '/lGamD2f6xEZJSoXlntAd5wvQnWZ.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [28, 14, 12],
    popularity: 5.2434,
    release_date: '2025-10-22',
    video: false,
    vote_average: 0.0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/6van4BavoNXaZhCPdzLHNQ4Uc8H.jpg',
    id: 1087891,
    title: 'The Amateur',
    original_title: 'The Amateur',
    overview:
      'After his life is turned upside down when his wife is killed in a London terrorist attack, a brilliant but introverted CIA decoder takes matters into his own hands when his supervisors refuse to take action.',
    poster_path: '/SNEoUInCa5fAgwuEBMIMBGvkkh.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [53, 28],
    popularity: 77.9368,
    release_date: '2025-04-09',
    video: false,
    vote_average: 7.019,
    vote_count: 795,
  },
  {
    adult: false,
    backdrop_path: '/hniP6c6Tss51qKc5vYMycDBDf9P.jpg',
    id: 1083433,
    title: 'I Know What You Did Last Summer',
    original_title: 'I Know What You Did Last Summer',
    overview:
      "When five friends inadvertently cause a deadly car accident, they cover up their involvement and make a pact to keep it a secret rather than face the consequences. A year later, their past comes back to haunt them and they're forced to confront a horrifying truth: someone knows what they did last summer…and is hell-bent on revenge.",
    poster_path: '/A06yXys3hrCWu8xiNoHCFLTG5SH.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [27, 9648, 53],
    popularity: 40.0372,
    release_date: '2025-07-16',
    video: false,
    vote_average: 6.3,
    vote_count: 15,
  },
  {
    adult: false,
    backdrop_path: '/fQOV47FHTJdaSuSUNlzP3zXUZWE.jpg',
    id: 1234821,
    title: 'Jurassic World Rebirth',
    original_title: 'Jurassic World Rebirth',
    overview:
      "Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.",
    poster_path: '/q0fGCmjLu42MPlSO9OYWpI5w86I.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [878, 12, 28],
    popularity: 289.6717,
    release_date: '2025-07-01',
    video: false,
    vote_average: 6.4,
    vote_count: 659,
  },
  {
    adult: false,
    backdrop_path: '/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg',
    id: 7451,
    title: 'xXx',
    original_title: 'xXx',
    overview:
      'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he\'s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.',
    poster_path: '/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [28, 12, 53, 80],
    popularity: 122.9854,
    release_date: '2002-08-09',
    video: false,
    vote_average: 5.948,
    vote_count: 4463,
  },
  {
    adult: false,
    backdrop_path: '/nZFgO3BDxpLzTpDXhYbdXBGdUVm.jpg',
    id: 936108,
    title: 'Smurfs',
    original_title: 'Smurfs',
    overview:
      'When Papa Smurf is mysteriously taken by evil wizards, Razamel and Gargamel, Smurfette leads the Smurfs on a mission into the real world to save him. With the help of new friends, the Smurfs must discover what defines their destiny to save the universe.',
    poster_path: '/8o6lkhL32xQJeB52IIG1us5BVey.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [16, 10751, 14],
    popularity: 36.0984,
    release_date: '2025-06-30',
    video: false,
    vote_average: 7.4,
    vote_count: 12,
  },
  {
    adult: false,
    backdrop_path: '/rthMuZfFv4fqEU4JVbgSW9wQ8rs.jpg',
    id: 986056,
    title: 'Thunderbolts*',
    original_title: 'Thunderbolts*',
    overview:
      'After finding themselves ensnared in a death trap, seven disillusioned castoffs must embark on a dangerous mission that will force them to confront the darkest corners of their pasts.',
    poster_path: '/hqcexYHbiTBfDIdDWxrxPtVndBX.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [28, 878, 12],
    popularity: 249.5951,
    release_date: '2025-04-30',
    video: false,
    vote_average: 7.431,
    vote_count: 1840,
  },
  {
    adult: false,
    backdrop_path: '/lkDYN0whyE82mcM20rwtwjbniKF.jpg',
    id: 911430,
    title: 'F1',
    original_title: 'F1',
    overview:
      'Racing legend Sonny Hayes is coaxed out of retirement to lead a struggling Formula 1 team—and mentor a young hotshot driver—while chasing one more chance at glory.',
    poster_path: '/9PXZIUsSDh4alB80jheWX4fhZmy.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [28, 18],
    popularity: 159.7575,
    release_date: '2025-06-25',
    video: false,
    vote_average: 7.639,
    vote_count: 790,
  },
  {
    adult: false,
    backdrop_path: '/7Q2CmqIVJuDAESPPp76rWIiA0AD.jpg',
    id: 1011477,
    title: 'Karate Kid: Legends',
    original_title: 'Karate Kid: Legends',
    overview:
      "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
    poster_path: '/AEgggzRr1vZCLY86MAp93li43z.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [28, 12, 18],
    popularity: 565.3801,
    release_date: '2025-05-08',
    video: false,
    vote_average: 7.275,
    vote_count: 436,
  },
  {
    adult: false,
    backdrop_path: '/g3lCbTn3HYHTiFrfusxKGXMdyUW.jpg',
    id: 533533,
    title: 'TRON: Ares',
    original_title: 'TRON: Ares',
    overview:
      "A highly sophisticated Program called Ares is sent from the digital world into the real world on a dangerous mission, marking humankind's first encounter with A.I. beings.",
    poster_path: '/chpWmskl3aKm1aTZqUHRCtviwPy.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [878, 12],
    popularity: 4.8727,
    release_date: '2025-10-08',
    video: false,
    vote_average: 0.0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/apNfldKI3RiaukNwJzr8EjRG7Wc.jpg',
    id: 1425045,
    title: 'Brick',
    original_title: 'Brick',
    overview:
      'When a mysterious brick wall encloses their apartment building overnight, Tim and Olivia must unite with their wary neighbors to get out alive.',
    poster_path: '/vTX9CxFNEQOlfXsgqec7xmc5UtD.jpg',
    media_type: 'movie',
    original_language: 'de',
    genre_ids: [53, 878],
    popularity: 127.1822,
    release_date: '2025-07-09',
    video: false,
    vote_average: 5.727,
    vote_count: 244,
  },
  {
    adult: false,
    backdrop_path: '/uIpJPDNFoeX0TVml9smPrs9KUVx.jpg',
    id: 574475,
    title: 'Final Destination Bloodlines',
    original_title: 'Final Destination Bloodlines',
    overview:
      'Plagued by a violent recurring nightmare, college student Stefanie heads home to track down the one person who might be able to break the cycle and save her family from the grisly demise that inevitably awaits them all.',
    poster_path: '/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [27, 9648],
    popularity: 210.5207,
    release_date: '2025-05-14',
    video: false,
    vote_average: 7.192,
    vote_count: 1647,
  },
  {
    adult: false,
    backdrop_path: '/sItIskd5xpiE64bBWYwZintkGf3.jpg',
    id: 541671,
    title: 'Ballerina',
    original_title: 'Ballerina',
    overview:
      'Taking place during the events of John Wick: Chapter 3 – Parabellum, Eve Macarro begins her training in the assassin traditions of the Ruska Roma.',
    poster_path: '/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [28, 53, 80],
    popularity: 363.6633,
    release_date: '2025-06-04',
    video: false,
    vote_average: 7.48,
    vote_count: 1022,
  },
  {
    adult: false,
    backdrop_path: '/nAxGnGHOsfzufThz20zgmRwKur3.jpg',
    id: 1233413,
    title: 'Sinners',
    original_title: 'Sinners',
    overview:
      'Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.',
    poster_path: '/4CkZl1LK6a5rXBqJB2ZP77h3N5i.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [27, 28, 53],
    popularity: 101.0956,
    release_date: '2025-04-16',
    video: false,
    vote_average: 7.568,
    vote_count: 2044,
  },
  {
    adult: false,
    backdrop_path: '/fd9K7ZDfzRAcbLh8JlG4HIKbtuR.jpg',
    id: 846422,
    title: 'The Old Guard 2',
    original_title: 'The Old Guard 2',
    overview:
      'Andy and her team of immortal warriors fight with renewed purpose as they face a powerful new foe threatening their mission to protect humanity.',
    poster_path: '/wqfu3bPLJaEWJVk3QOm0rKhxf1A.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [28, 14],
    popularity: 265.1465,
    release_date: '2025-07-01',
    video: false,
    vote_average: 6.08,
    vote_count: 484,
  },
  {
    adult: false,
    backdrop_path: '/rJjhOuRFldNF0OWSuSk4PiCLmeA.jpg',
    id: 803796,
    title: 'KPop Demon Hunters',
    original_title: 'KPop Demon Hunters',
    overview:
      "When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to protect their fans from supernatural threats.",
    poster_path: '/jfS5KEfiwsS35ieZvdUdJKkwLlZ.jpg',
    media_type: 'movie',
    original_language: 'en',
    genre_ids: [16, 14, 28, 35, 10402, 10751],
    popularity: 209.9166,
    release_date: '2025-06-20',
    video: false,
    vote_average: 8.596,
    vote_count: 645,
  },
];

export const fantasticFourDetailsMock: MovieDetails = {
  adult: false,
  backdrop_path: '/s94NjfKkcSczZ1FembwmQZwsuwY.jpg',
  belongs_to_collection: null,
  budget: 200000000,
  genres: [
    {
      id: 878,
      name: 'Science Fiction',
    },
    {
      id: 12,
      name: 'Adventure',
    },
  ],
  homepage: 'https://www.marvel.com/movies/the-fantastic-four-first-steps',
  id: 617126,
  imdb_id: 'tt10676052',
  origin_country: ['US'],
  original_language: 'en',
  original_title: 'The Fantastic 4: First Steps',
  overview:
    "Against the vibrant backdrop of a 1960s-inspired, retro-futuristic world, Marvel's First Family is forced to balance their roles as heroes with the strength of their family bond, while defending Earth from a ravenous space god called Galactus and his enigmatic Herald, Silver Surfer.",
  popularity: 405.4341,
  poster_path: '/x26MtUlwtWD26d0G0FXcppxCJio.jpg',
  production_companies: [
    {
      id: 420,
      logo_path: '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
      name: 'Marvel Studios',
      origin_country: 'US',
    },
    {
      id: 176762,
      logo_path: null,
      name: 'Kevin Feige Productions',
      origin_country: 'US',
    },
  ],
  production_countries: [
    {
      iso_3166_1: 'US',
      name: 'United States of America',
    },
  ],
  release_date: '2025-07-23',
  revenue: 216835810,
  runtime: 115,
  spoken_languages: [
    {
      english_name: 'English',
      iso_639_1: 'en',
      name: 'English',
    },
  ],
  status: 'Released',
  tagline: 'Welcome to the family.',
  title: 'The Fantastic 4: First Steps',
  video: false,
  vote_average: 7.347,
  vote_count: 606,
};

const mockMovieDetails: MovieDetails = {
  adult: false,
  backdrop_path: '/fncHijpWjitFBmj7SX5z148XEhP.jpg',
  belongs_to_collection: {
    id: 328,
    name: 'Jurassic Park Collection',
    poster_path: '/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg',
    backdrop_path: '/njFixYzIxX8jsn6KMSEtAzi4avi.jpg',
  },
  budget: 180000000,
  genres: [
    {
      id: 878,
      name: 'Science Fiction',
    },
    {
      id: 12,
      name: 'Adventure',
    },
    {
      id: 28,
      name: 'Action',
    },
  ],
  homepage: 'https://www.jurassicworld.com',
  id: 1234821,
  imdb_id: 'tt31036941',
  origin_country: ['US'],
  original_language: 'en',
  original_title: 'Jurassic World Rebirth',
  overview:
    "Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.",
  popularity: 1236.3748,
  poster_path: '/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg',
  production_companies: [
    {
      id: 33,
      logo_path: '/6exxhPonOo0M995SAchY0ijpRao.png',
      name: 'Universal Pictures',
      origin_country: 'US',
    },
    {
      id: 56,
      logo_path: '/cEaxANEisCqeEoRvODv2dO1I0iI.png',
      name: 'Amblin Entertainment',
      origin_country: 'US',
    },
  ],
  production_countries: [
    {
      iso_3166_1: 'US',
      name: 'United States of America',
    },
  ],
  release_date: '2025-07-01',
  revenue: 778134467,
  runtime: 134,
  spoken_languages: [
    {
      english_name: 'English',
      iso_639_1: 'en',
      name: 'English',
    },
    {
      english_name: 'French',
      iso_639_1: 'fr',
      name: 'Français',
    },
  ],
  status: 'Released',
  tagline: 'A new era is born.',
  title: 'Jurassic World Rebirth',
  video: false,
  vote_average: 6.404,
  vote_count: 1302,
};

const mockMovieResponse = {
  page: 1,
  total_pages: 20,
  results: mockMovies,
};

export { mockMovies, mockMovieDetails, mockMovieResponse };
